development:
  adapter: mysql2
  database: f_change_develop
  username: root
  password: '1'
  host: '127.0.0.1'
  port: 3306
  strict: false

production:
  adapter: mysql2
  database: f_change_prod
  username: root
  password: '1'
  host: '127.0.0.1'
  port: 3306
  strict: false

test:
  adapter: mysql2
  database: f_change_test
  username: root
  password: '1'
  host: '127.0.0.1'
  port: 3306
  strict: false
