# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acc53aebe7abc4376277700d93d931c755197d073f9383ab0d68123c686da4c2129a4af851dfaec34bcbf388f25a9ee74c655b67e5044e0b567261d0a8080a91

test:
  secret_key_base: d54aabca9dd3a50b8e08c11995e6261796120fb7723b4da4551046665cf6647e79524220b4f74537cb2f673b2e1b53db88938f7a77dfd4c32e7d2a2bfa8846a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
